@startuml
node "kart server instance" {
  interface HTTP as ServerInfoHTTP
  interface UDP as ServerInfoUDP

  database Volume

  [Srb2Kart] - ServerInfoUDP
  [Srb2KartTranslator] - ServerInfoHTTP

  Srb2KartTranslator --> ServerInfoUDP

  Srb2Kart --> Volume
}

node "Replays" {
  interface HTTP as ReplayInfoHTTP
  interface HTTP as ReplayUploadHTTP
  interface HTTP as ReplayStaffHTTP

  [ReplayServer] -left- ReplayInfoHTTP
  [ReplayIngest] -left- ReplayUploadHTTP
  [ReplayStaff] -left- ReplayStaffHTTP

  database ReplayInfo
  database ReplayVolume

  ReplayServer ---> ReplayInfo
  ReplayIngest --right-> ReplayInfoHTTP

  ReplayIngest ---> ReplayVolume
  ReplayStaff ---> ReplayVolume
}

node Discord {
  [ClientOwner]
  [DiscordStatus] 

  package Commands {
    [/players] ---> ServerInfoHTTP

    package "/replays" {
      [/replay download] ---> ReplayStaffHTTP
      [/replay upload] ---> ReplayUploadHTTP
      [/replay search] ---> ReplayInfoHTTP
    }
  }

  DiscordStatus -up-> ServerInfoHTTP 

  ClientOwner -right-> Commands
  ClientOwner --> DiscordStatus
}

' Works in Progres
/'
node Website {
  [StatusUI] -->  ServerInfoHTTP
  [AddonUI] --> AddonCRUDHTTP
}
'/

/'
node "Command Line" {
  package "CLI Commands" {
    [cli Status]
    [cli Addons]
    [cli Server Instance]

    [cli Status] --> ServerInfoHTTP
    [cli Addons] --> AddonCRUDHTTP
    [cli Server Instance]
  }
}
'/

/'
node "Instance Management TODO" {
}
'/

/'
node "Addon Management" {
  interface HTTP as AddonCRUDHTTP
  [AddonCRUD] - AddonCRUDHTTP

  database AddonMetadata

  AddonCRUD --> AddonMetadata
}
'/

@enduml
